from django.urls import path

from . import views

urlpatterns = [
  path("", views.TopPageView.as_view(), name="top_page"),
  path("company/", views.CompanyView.as_view(), name="company_page"),
  path("terms/", views.TermsView.as_view(), name="terms_page"),
  path("restaurant-detail/<int:pk>/", views.RestaurantDetailView.as_view(), name="restaurant_detail"),
  path("restaurant-list/", views.RestaurantListView.as_view(), name="restaurant_list"),
  path("favorite-list/", views.FavoriteListView.as_view(), name="favorite_list"),
  path("favorite-delete/", views.favorite_delete, name="favorite_delete"),
  path('reservation-create/<int:pk>/', views.ReservationCreateView.as_view(), name="reservation_create"),
  path("reservation-list/", views.ReservationListView.as_view(), name="reservation_list"),
  path('reservation-delete', views.reservation_delete, name='reservation_delete'),
  path('review-list/<int:pk>/', views.ReviewListView.as_view(), name="review_list"),
  path('review-create/<int:pk>/', views.ReviewCreateView.as_view(), name="review_create"),
  path('review-update/<int:pk>/', views.ReviewUpdateView.as_view(), name="review_update"),
  path('review-delete', views.review_delete, name='review_delete'),
  path("restaurant-list-2/<int:pk>/", views.RestaurantListView2.as_view(), name="restaurant_list_2"),
  path("restaurant-create/", views.RestaurantCreateView.as_view(), name="restaurant_create"),
  path("restaurant-update/<int:pk>/", views.RestaurantUpdateView.as_view(), name="restaurant_update"),
  path('restaurant/<int:restaurant_id>/dining-tables/', views.DiningTableListView.as_view(), name='dining_table_list'),
  path('restaurant/<int:restaurant_id>/dining-tables/update/<int:pk>/', views.DiningTableUpdateView.as_view(), name='dining_table_update'),
  path('restaurant/<int:restaurant_id>/dining-tables/<int:pk>/delete/', views.dining_table_delete, name='dining_table_delete'),
  path('restaurant/<int:restaurant_id>/dining-tables/create/', views.DiningTableCreateView.as_view(), name='dining_table_create'),
  # path('restaurant/<int:restaurant_id>/dining_table/delete/<int:pk>/', views.DiningTableDeleteView.as_view(), name='dining_table_delete'),
  # path('restaurant/<int:restaurant_id>/dining-tables/<int:pk>/', views.DiningTableDeleteView.as_view(), name='dining_table_delete'),
  path('restaurant/<int:restaurant_id>/menu/', views.MenuListView.as_view(), name='menu_list'),
  path('restaurant/<int:restaurant_id>/menu/update/<int:pk>/', views.MenuUpdateView.as_view(), name='menu_update'),
  path('restaurant/<int:restaurant_id>/menu/create/', views.MenuCreateView.as_view(), name='menu_create'),
  path('restaurant/<int:restaurant_id>/menu/delete/<int:pk>/', views.MenuDeleteView.as_view(), name='menu_delete'),
  path('restaurants/<int:pk>/reviews/', views.ReviewListView2.as_view(), name='review_list2'),
  path('reviews/<int:pk>/edit/', views.ReviewUpdateView2.as_view(), name='review_update2'),
  path('reviews/<int:pk>/toggle-display/', views.toggle_display_masked, name='toggle_display_masked'),
  path('restaurants/reservation/reservation-management/<int:restaurant_id>/', views.ReservationManagementView.as_view(), name='reservation_management'),
  # path('reservation-management/', views.ReservationManagementView.as_view(), name='reservation_management'),
  ]