# Generated by Django 4.2 on 2024-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiry',
            field=models.DateField(blank=True, null=True, verbose_name='カード有効期限'),
        ),
    ]
