# Generated by Django 4.2 on 2024-09-15 10:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='カテゴリー名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_for_internal', models.CharField(max_length=64, verbose_name='卓名（店舗管理用）')),
                ('name_for_customer', models.CharField(max_length=64, verbose_name='卓名（HP表示用）')),
                ('min_people', models.IntegerField(choices=[('', '選択してください'), (1, '1名'), (2, '2名'), (3, '3名'), (4, '4名'), (5, '5名'), (6, '6名'), (7, '7名'), (8, '8名'), (9, '9名'), (10, '10名'), (11, '11名'), (12, '12名'), (13, '13名'), (14, '14名'), (15, '15名'), (16, '16名'), (17, '17名'), (18, '18名'), (19, '19名'), (20, '20名'), (21, '21名'), (22, '22名'), (23, '23名'), (24, '24名'), (25, '25名'), (26, '26名'), (27, '27名'), (28, '28名'), (29, '29名'), (30, '30名'), (31, '31名'), (32, '32名'), (33, '33名'), (34, '34名'), (35, '35名'), (36, '36名'), (37, '37名'), (38, '38名'), (39, '39名'), (40, '40名'), (41, '41名'), (42, '42名'), (43, '43名'), (44, '44名'), (45, '45名'), (46, '46名'), (47, '47名'), (48, '48名'), (49, '49名'), (50, '50名')], default='', verbose_name='最少人数')),
                ('max_people', models.IntegerField(choices=[('', '選択してください'), (1, '1名'), (2, '2名'), (3, '3名'), (4, '4名'), (5, '5名'), (6, '6名'), (7, '7名'), (8, '8名'), (9, '9名'), (10, '10名'), (11, '11名'), (12, '12名'), (13, '13名'), (14, '14名'), (15, '15名'), (16, '16名'), (17, '17名'), (18, '18名'), (19, '19名'), (20, '20名'), (21, '21名'), (22, '22名'), (23, '23名'), (24, '24名'), (25, '25名'), (26, '26名'), (27, '27名'), (28, '28名'), (29, '29名'), (30, '30名'), (31, '31名'), (32, '32名'), (33, '33名'), (34, '34名'), (35, '35名'), (36, '36名'), (37, '37名'), (38, '38名'), (39, '39名'), (40, '40名'), (41, '41名'), (42, '42名'), (43, '43名'), (44, '44名'), (45, '45名'), (46, '46名'), (47, '47名'), (48, '48名'), (49, '49名'), (50, '50名')], default='', verbose_name='最大人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Dining Table',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=32, verbose_name='郵便番号')),
                ('shop_name', models.CharField(max_length=64, verbose_name='店舗名')),
                ('address', models.CharField(max_length=128, verbose_name='住所')),
                ('phone', models.CharField(max_length=32, verbose_name='電話番号')),
                ('owner_name', models.CharField(max_length=64, verbose_name='代表者名')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='メールアドレス')),
                ('description', models.CharField(max_length=128, verbose_name='説明')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('business_time', models.CharField(max_length=64, verbose_name='営業時間')),
                ('close_day_of_week', models.CharField(max_length=32, verbose_name='定休日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.category', verbose_name='カテゴリー')),
                ('shop_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='店舗オーナー')),
            ],
            options={
                'verbose_name_plural': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='訪問日')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='レート')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='回答')),
                ('display_masked', models.IntegerField(default='0', verbose_name='非表示フラグ')),
                ('comment_created_at', models.DateTimeField(auto_now_add=True, verbose_name='レビュー作成日時')),
                ('comment_updated_at', models.DateTimeField(auto_now=True, verbose_name='レビュー更新日時')),
                ('reply_created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答作成日時')),
                ('reply_updated_at', models.DateTimeField(auto_now=True, verbose_name='回答更新日時')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='会員')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant', verbose_name='レストラン')),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='予約日')),
                ('time_start', models.TimeField(choices=[('', '選択してください'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], default='', verbose_name='予約開始時間')),
                ('time_end', models.TimeField(choices=[('', '選択してください'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], default='', verbose_name='予約終了時間')),
                ('number_of_people', models.IntegerField(choices=[('', '選択してください'), (1, '1名'), (2, '2名'), (3, '3名'), (4, '4名'), (5, '5名'), (6, '6名'), (7, '7名'), (8, '8名'), (9, '9名'), (10, '10名'), (11, '11名'), (12, '12名'), (13, '13名'), (14, '14名'), (15, '15名'), (16, '16名'), (17, '17名'), (18, '18名'), (19, '19名'), (20, '20名'), (21, '21名'), (22, '22名'), (23, '23名'), (24, '24名'), (25, '25名'), (26, '26名'), (27, '27名'), (28, '28名'), (29, '29名'), (30, '30名'), (31, '31名'), (32, '32名'), (33, '33名'), (34, '34名'), (35, '35名'), (36, '36名'), (37, '37名'), (38, '38名'), (39, '39名'), (40, '40名'), (41, '41名'), (42, '42名'), (43, '43名'), (44, '44名'), (45, '45名'), (46, '46名'), (47, '47名'), (48, '48名'), (49, '49名'), (50, '50名')], default='', verbose_name='人数')),
                ('is_booked', models.IntegerField(default='0', verbose_name='予約済みフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='予約受付日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='予約更新日時')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='会員')),
                ('dining_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.diningtable', verbose_name='卓情報')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant', verbose_name='レストラン')),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='お気に入り登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='お気に入り更新日時')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='会員')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant', verbose_name='レストラン')),
            ],
            options={
                'verbose_name_plural': 'Favorite',
            },
        ),
        migrations.AddField(
            model_name='diningtable',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant', verbose_name='レストラン'),
        ),
    ]
