# Generated by Django 4.2 on 2024-09-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_favorite_customer_alter_reservation_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
    ]
