# Generated by Django 4.2 on 2024-09-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Restaurant'},
        ),
    ]
