# Generated by Django 4.2 on 2024-09-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='営業時間'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_day_of_week',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='定休日'),
        ),
    ]
