# Generated by Django 4.2 on 2024-09-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_business_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateField(verbose_name='訪問日'),
        ),
    ]
