# Generated by Django 4.2 on 2024-09-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_review_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reply_created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reply_updated_at',
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='回答')),
                ('display_masked', models.IntegerField(default='0', verbose_name='非表示フラグ')),
                ('comment_created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答作成日時')),
                ('comment_updated_at', models.DateTimeField(auto_now=True, verbose_name='回答更新日時')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.review', verbose_name='レビュー')),
            ],
            options={
                'verbose_name_plural': 'Reply',
            },
        ),
    ]
