# Generated by Django 4.2 on 2024-09-16 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_review_reply_remove_review_reply_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'verbose_name_plural': 'Review Reply'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(blank=True, choices=[('', '選択してください'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], default='', null=True, verbose_name='予約終了時間'),
        ),
    ]
