# Generated by Django 4.2 on 2024-09-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_reservation_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_booked',
            field=models.BooleanField(default='0', verbose_name='予約済みフラグ'),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='display_masked',
            field=models.BooleanField(default='0', verbose_name='非表示フラグ'),
        ),
    ]
