# Generated by Django 4.2 on 2024-09-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_reservation_is_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='display_masked',
            field=models.BooleanField(default='0', verbose_name='非表示フラグ'),
        ),
    ]
