# Generated by Django 4.2 on 2024-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_reservation_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name='レート'),
        ),
    ]
