# Generated by Django 4.2 on 2024-09-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_reservation_time_end_reservation_duration_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='reviewreply',
            old_name='comment_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewreply',
            old_name='comment_updated_at',
            new_name='updated_at',
        ),
    ]
