# Generated by Django 4.2 on 2024-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_rename_comment_created_at_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='返信'),
        ),
        migrations.DeleteModel(
            name='ReviewReply',
        ),
    ]
