# Generated by Django 4.2 on 2024-09-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_remove_restaurant_category_restaurant_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='categories',
            new_name='category',
        ),
    ]
