# Generated by Django 4.2 on 2024-09-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_rename_categories_restaurant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='restaurant.category', verbose_name='カテゴリー'),
            preserve_default=False,
        ),
    ]
