# Generated by Django 4.2 on 2024-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_restaurant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='最高価格'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='最低価格'),
        ),
    ]
