# Generated by Django 4.2.16 on 2024-10-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_restaurant_rate_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dining_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.diningtable', verbose_name='卓情報'),
        ),
    ]
