# Generated by Django 4.2.16 on 2024-10-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_alter_reservation_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格（一名分）'),
        ),
    ]
